name: momo_fraud
version: '1.0.0'
config-version: 2

profile: momo_fraud

model-paths: ["models"]
test-paths:  ["tests"]

models:
  momo_fraud:
    staging:
      +materialized: view
      +schema: staging      # → hive.staging.*
    warehouse:
      +materialized: incremental
      +schema: warehouse    # → hive.warehouse.*
    marts:
      +materialized: table
      +schema: warehouse    # → hive.warehouse.*
