momo_fraud:
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      user: airflow
      host: trino
      port: 8080
      database: hive
      schema: warehouse    # dbt sẽ write vào hive.warehouse.*
      threads: 4

    prod:
      type: trino
      method: none
      user: airflow
      host: trino
      port: 8080
      database: hive
      schema: warehouse
      threads: 8
