# Trino coordinator config
# Trong dev: coordinator và worker là cùng 1 node (single-node mode)
# Production: coordinator riêng, nhiều worker nodes riêng

coordinator=true
node-scheduler.include-coordinator=true

http-server.http.port=8080

query.max-memory=8GB
query.max-memory-per-node=4GB
query.max-total-memory-per-node=6GB

discovery.uri=http://localhost:8080
