# Trino Hive Connector — kết nối Trino vào Hive Metastore để query HDFS
# Đây là "catalog" trong Trino: khi query "SELECT * FROM hive.staging.transactions"
# phần "hive." chính là catalog này

connector.name=hive

hive.metastore.uri=thrift://hive-metastore:9083

hive.non-managed-table-writes-enabled=true
hive.metastore-cache-ttl=1m
hive.metastore-refresh-interval=1m

hive.config.resources=/etc/trino/hdfs/core-site.xml,/etc/trino/hdfs/hdfs-site.xml

hive.parquet.use-column-names=true
hive.compression-codec=SNAPPY
hive.allow-drop-table=true
